name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.20'
          - '5.22'
          - '5.30'
          - '5.32'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Init cache
        uses: actions/cache@v2
        with:
          path: ~/.perl-cpm/builds
          key: ${{ runner.os }}-${{ matrix.perl-version }}-${{ hashFiles('**/cpanfile') }}
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@stable
        with:
          cpanfile: "cpanfile"
          sudo: false
      - name: Build Alien::libccv
        run: perl Makefile.PL && make
      - name: Run tests
        run: prove
