name: macos
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Perl
        run: brew install perl
      - name: perl -V
        run: perl -V
      - name: Init cache
        uses: actions/cache@v2
        with:
          path: ~/.perl-cpm/builds
          key: ${{ runner.os }}-${{ hashFiles('**/cpanfile') }}
      - name: Install dependencies
        uses: perl-actions/install-with-cpm@stable
        with:
          cpanfile: "cpanfile"
          sudo: false
      - name: Build Alien::libccv
        run: perl Makefile.PL && make
      - name: Run Tests
        run: prove
